version: '3.8'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    volumes:
      - ./kong_datastore:/var/lib/postgresql/data
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - '5432:5432'

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: 'kong migrations bootstrap'
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      # KONG_PROXY_LISTEN: 0.0.0.0:8000
      # KONG_ADMIN_LISTEN: 0.0.0.0:8001
      # KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - kong-migration
      - kong-database

    ports:
      - '8001:8001'
      - '8000:8000'
      - '8444:8444'
      - '8443:8443'

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: '-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db'
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong
      TOKEN_SECRET: somerandomstring
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - '1337:1337'

  #######################################
  # Node FCM Serices
  #######################################
  node-fcm:
    image: winz7/node-fcm
    restart: always
    networks:
      - kong-net
    ports:
      - '8088:8088'
      - '8448:8448'
    depends_on:
      - kong
      - kong-database

  #######################################
  # Prometheus
  #######################################
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    restart: always
    networks:
      - kong-net
    ports:
      - 9090:9090

  #######################################
  # Node Exporter
  #######################################
  node_exporter:
    image: prom/node-exporter:latest
    restart: always
    networks:
      - kong-net
    ports:
      - 9100:9100

  #######################################
  # Grafana Dashboard
  #######################################
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - kong-net
    ports:
      - 3000:3000
